### PR TITLE
feat(about-us page): create about-us page

### PR DESCRIPTION
**Pull request by laviedegeorge**
#11

#### What does this PR do
Create About-Us Page

#### Description of Task to be completed
Web design for About-us page

#### How should this be manually tested
Pull this branch
visit localhost:8000/about-us
View the page

#### What are the relevant issues this PR belongs to

#11 

#### Any background context you want to add
Nil

### CODE REVIEW

**Comment by Princesso** [comment]
Thanks for raising this PR, please could you write tests for the new feature? I think someone added gotham fonts, I'll confirm and get back to you on this thread.

**Comment by laviedegeorge** [comment]
> 
> 
> Thanks for raising this PR, please could you write tests for the new feature? I think someone added gotham fonts, I'll confirm and get back to you on this thread.

Hi! what type of test should i write?

**Comment by Princesso** [comment]
end-2-end test with cypress and snapshot test with jest, there are examples. Also kindly investigate why this build is failing.

**Comment by laviedegeorge** [comment]
ok, I will investigate why the build is failing, I have never written a cypress and jest test before.

**Comment by laviedegeorge** [comment]
I tried the build command on my PC and everything works fine. Can't see why the build is failing, I would really appreciate it if I can get help.

**Comment by Princesso** [comment]
Kindly check for me email id on my profile and schedule a 20 minute call between 10:30am and 12 noon

**Comment by laviedegeorge** [comment]
Hi! sorry, I am just seeing this now.
are you available today?

**Pull request closed without merging**
